const Map<String, String> countryNameMap = const {
  'AUD': 'Australia - Dollar',
  'BGN': 'Bulgaria - Lev',
  'BRL': 'Brazil - Real',
  'CAD': 'Canada - Dollar',
  'CHF': 'Switzerland - Franc',
  'CNY': 'China - Yuan',
  'CZK': 'Czech Republic - Koruna',
  'DKK': 'Denmark - Krone',
  'EUR': 'Euro Member Countries',
  'GBP': 'United Kingdom - Pound',
  'HKD': 'Hong Kong - Dollar',
  'HRK': 'Croatia - Kuna',
  'HUF': 'Hungary - Forint',
  'IDR': 'Indonesia - Rupiah',
  'ILS': 'Israel - Shekel',
  'INR': 'India - Rupee',
  'ISK': 'Iceland - Krona',
  'JPY': 'Japan - Yen',
  'KRW': 'South Korea - Won',
  'MXN': 'Mexico - Peso',
  'MYR': 'Malaysia - Ringgit',
  'NOK': 'Norway - Krone',
  'NZD': 'New Zealand - Dollar',
  'PHP': 'Philippines - Piso',
  'PLN': 'Poland - Zloty',
  'RON': 'Romania - Leu',
  'RUB': 'Russia - Ruble',
  'SEK': 'Sweden - Krona',
  'SGD': 'Singapore - Dollar',
  'THB': 'Thailand - Baht',
  'TRY': 'Turkey - Lira',
  'USD': 'United States - Dollar',
  'ZAR': 'South Africa - Rand',
};